name: Code Quality Checks
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint-format-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22"

            - name: Install dependencies
              run: npm install

            - name: Format code
              run: npm run format

            - name: Lint code
              run: npm run lint

            - name: Build project
              run: npm run build
